version: '3'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - AZURE_STORAGE_CONNECTION_STRING
  silo:
    image: silo
    build:
      context: .
      dockerfile: Silo/Dockerfile
    environment:
      - AZURE_STORAGE_CONNECTION_STRING
